# This workflow installs Python dependencies, runs tests, and performs linting for the CHDDOS project.
# For more information, see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

# CHDDOS Legal Disclaimer:
# CHDDOS is developed by ChillHack Hong Kong Web Development (https://chillhack.net, info@chillhack.net)
# solely for authorized penetration testing and educational purposes. Unauthorized use for cyber attacks
# is illegal and carries extremely high legal consequences under global cybersecurity laws, including
# the Computer Fraud and Abuse Act (CFAA), EU Cybersecurity Act, and Hong Kong Computer Crimes Ordinance.
# ChillHack and its contributors are not responsible for any misuse or damage caused by this tool.
# Always obtain explicit permission from the target system's owner before conducting any tests.

name: CHDDOS Python Application CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install aiohttp scapy dnspython pysocks tqdm psutil requests colorama flake8 pytest
        # Create requirements.txt for reference
        pip freeze > requirements.txt
    - name: Lint with flake8
      run: |
        # Stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Relaxed linting for CHDDOS: allow higher complexity and longer lines
        flake8 . --count --exit-zero --max-complexity=15 --max-line-length=150 --statistics
    - name: Test with pytest
      run: |
        # CHDDOS is a penetration testing tool; standard unit tests may not apply
        # Run pytest if test files exist, otherwise skip
        if [ -d tests ]; then pytest; else echo "No tests found, skipping pytest"; fi
